name: Deploy to GitHub Pages

on:
  push:
    branches:
      - git-workflow  # Triggers the workflow on push to the main branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-with: 20
          cache: 'npm' # Caches npm packages for faster subsequent builds

      - name: Install Dependencies
        run: npm ci # 'npm ci' is preferred in automated environments over 'npm install'

      - name: Build Project
        run: npm run build

      # GitHub Pages action expects an artifact upload. 
      # Note: Adjust the 'path' below if your framework outputs to a different folder (like 'build' or 'dist/your-app-name')
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4